### PR TITLE
Update README.md

### LINKED ISSUE #4: Description - A *package* for testing subprocesses?
RE Readme/pubspec

### LINKED ISSUE #2427: Description - A *package* for testing subprocesses?
RE Readme/pubspec

### PR DESCRIPTION
**Pull request by nex3**
Closes dart-lang/test#2427

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
And pubspec description?

**Comment by nex3** [comment]
Huh?

**Comment by kevmoo** [comment]
https://github.com/dart-lang/test_process/blob/master/pubspec.yaml#L3 – also says "library"

**Comment by nex3** [comment]
PTAL

**Review by kevmoo — APPROVED** [review]

**Pull request merged**
